export const AUTHENTICATION_SERVICE_TOKEN = Symbol(
  'AUTHENTICATION_SERVICE_TOKEN'
);
export const NAVIGATION_SERVICE_TOKEN = Symbol('NAVIGATION_SERVICE_TOKEN');
export const TENANT_MANAGEMENT_SERVICE_TOKEN = Symbol(
  'TENANT_MANAGEMENT_SERVICE_TOKEN'
);
